"""Persistent analytics events emitted by scheduling and eco-score routes."""

from __future__ import annotations

from datetime import datetime, timezone

from extensions import db


class AnalyticsRecommendation(db.Model):
    """A recommendation generated by the optimizer."""

    __tablename__ = "analytics_recommendations"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    activity_id = db.Column(
        db.String(64),
        db.ForeignKey("activities.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    text = db.Column(db.Text, nullable=False)
    reason = db.Column(db.Text, nullable=False)
    expected_carbon_saving = db.Column(db.Float, nullable=True)
    expected_energy_saving = db.Column(db.Float, nullable=True)
    status = db.Column(db.String(32), nullable=False)
    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "activityId": self.activity_id,
            "text": self.text,
            "reason": self.reason,
            "expectedCarbonSaving": self.expected_carbon_saving,
            "expectedEnergySaving": self.expected_energy_saving,
            "status": self.status,
            "timestamp": self.created_at.isoformat(),
        }
